server {
    listen 80;
    server_name media.example.com;

    root /media/emom_2tb;
    autoindex off;

    location = /.well-known/gallery-manifest.json {
        default_type application/json;
        add_header Cache-Control "no-cache, must-revalidate";
        try_files $uri =404;
    }

    location / {
        try_files $uri =404;
    }
}
