server {
    listen 80;
    server_name media.example.com;

    root /media/emom_2tb;
    autoindex off;

    location = /.well-known/gallery-manifest.json {
        default_type application/json;
        add_header Cache-Control "no-cache, must-revalidate";
        try_files $uri =404;
    }

    location / {
        try_files $uri =404;
    }
}

server {
    listen 443 ssl;
    http2 on;
    server_name media.example.com;

    ssl_certificate /etc/letsencrypt/live/my.domain/fullchain.pem;
    ssl_certificate_key /etc/letsencrypt/live/my.domain/privkey.pem;

    root /media/emom_2tb;
    autoindex off;

    location = /.well-known/gallery-manifest.json {
        default_type application/json;
        add_header Cache-Control "no-cache, must-revalidate";
        try_files $uri =404;
    }

    location / {
        try_files $uri =404;
    }
}
